In [1]:
data_url = 'https://www.kaggle.com/niyamatalmass/google-job-skills#job_skills.csv'

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
pd.set_option('display.max_colwidth', 70)

In [4]:
ggorig = pd.read_csv('job_skills.csv')

ggorig.head()

,Company,Title,Category,Location,Responsibilities,Minimum Qualifications,Preferred Qualifications
0,Google,Google Cloud Program Manager,Program Management,Singapore,"Shape, shepherd, ship, and show technical programs designed to sup...",BA/BS degree or equivalent practical experience.\n3 years of exper...,Experience in the business technology market as a program manager ...
1,Google,"Supplier Development Engineer (SDE), Cable/Connector",Manufacturing & Supply Chain,"Shanghai, China",Drive cross-functional activities in the supply chain for overall ...,BS degree in an Engineering discipline or equivalent practical exp...,"BSEE, BSME or BSIE degree.\nExperience of using Statistics tools f..."
2,Google,"Data Analyst, Product and Tools Operations, Google Technical Services",Technical Solutions,"New York, NY, United States",Collect and analyze data to draw insight and identify strategic so...,"Bachelor’s degree in Business, Economics, Statistics, Operations R...",Experience partnering or consulting cross-functionally with senior...
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States","Work one-on-one with the top Android, iOS, and web engineers to bu...",BA/BS degree in Computer Science or equivalent practical experienc...,"Experience as a software developer, architect, technology advocate..."
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",Plan requirements with internal customers.\nProvide portfolio repo...,BA/BS degree or equivalent practical experience.\n4 years of exper...,CTS Certification.\nExperience in the construction sector.\nExperi...

In [5]:
ggorig['Location'].value_counts()[:5]

Mountain View, CA, United States    190
Sunnyvale, CA, United States        155
Dublin, Ireland                      87
New York, NY, United States          70
London, United Kingdom               62
Name: Location, dtype: int64

In [6]:
ggms = ggorig[(ggorig['Location'] == 'Mountain View, CA, United States') |
              (ggorig['Location'] == 'Sunnyvale, CA, United States')]
ggms.shape

(345, 7)

In [7]:
ggms.head()

,Company,Title,Category,Location,Responsibilities,Minimum Qualifications,Preferred Qualifications
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States","Work one-on-one with the top Android, iOS, and web engineers to bu...",BA/BS degree in Computer Science or equivalent practical experienc...,"Experience as a software developer, architect, technology advocate..."
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",Plan requirements with internal customers.\nProvide portfolio repo...,BA/BS degree or equivalent practical experience.\n4 years of exper...,CTS Certification.\nExperience in the construction sector.\nExperi...
6,Google,"Supplier Development Engineer, Camera, Consumer Hardware",Hardware Engineering,"Mountain View, CA, United States",Manage cross-functional activities in the supply chain for overall...,BS degree in Engineering or equivalent practical experience.\n10 y...,Master's degree.\nExperience in the development of camera module i...
7,Google,"Strategic Technology Partner Manager, Healthcare and Life Sciences",Partnerships,"Sunnyvale, CA, United States",Lead the development and strategy with partners for healthcare and...,BA/BS degree or equivalent practical experience.\n5 years of exper...,"BA/BS degree in a technical, life sciences or engineering field or..."
10,Google,"Data Analyst, Consumer Hardware",Product & Customer Support,"Mountain View, CA, United States",Build and maintain the Support Operations Analytics infrastructure...,"BA/BS degree in Computer Science, Engineering, Economics, Business...","Experience in designing and executing structured analysis, derivin..."

Text average length

In [8]:
ggms['r_count'] = ggms['Responsibilities'].apply(lambda x:
                                                 len(str(x).split(" ")))
ggms[['Responsibilities', 'r_count']].head()

C:\Users\liamk\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Responsibilities,r_count
3,"Work one-on-one with the top Android, iOS, and web engineers to bu...",82
4,Plan requirements with internal customers.\nProvide portfolio repo...,99
6,Manage cross-functional activities in the supply chain for overall...,79
7,Lead the development and strategy with partners for healthcare and...,131
10,Build and maintain the Support Operations Analytics infrastructure...,70

In [9]:
ggms['m_count'] = ggms['Minimum Qualifications'].apply(lambda x:
                                                      len(str(x).split(" ")))
ggms[['Minimum Qualifications', 'm_count']].head()

C:\Users\liamk\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Minimum Qualifications,m_count
3,BA/BS degree in Computer Science or equivalent practical experienc...,27
4,BA/BS degree or equivalent practical experience.\n4 years of exper...,31
6,BS degree in Engineering or equivalent practical experience.\n10 y...,25
7,BA/BS degree or equivalent practical experience.\n5 years of exper...,43
10,"BA/BS degree in Computer Science, Engineering, Economics, Business...",43

In [10]:
ggms['p_count'] = ggms['Preferred Qualifications'].apply(lambda x:
                                                         len(str(x).split(" ")))
ggms[['Preferred Qualifications', 'p_count']].head()

C:\Users\liamk\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Preferred Qualifications,p_count
3,"Experience as a software developer, architect, technology advocate...",35
4,CTS Certification.\nExperience in the construction sector.\nExperi...,41
6,Master's degree.\nExperience in the development of camera module i...,45
7,"BA/BS degree in a technical, life sciences or engineering field or...",78
10,"Experience in designing and executing structured analysis, derivin...",91

In [11]:
print(ggms.mean())
print('Average word length: responsibilities is longest, followed by Preferred and Minimum')

r_count    86.356522
m_count    31.756522
p_count    62.049275
dtype: float64
Average word length: responsibilities is longest, followed by Preferred and Minimum

In [12]:
ggms.head()

,Company,Title,Category,Location,Responsibilities,Minimum Qualifications,Preferred Qualifications,r_count,m_count,p_count
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States","Work one-on-one with the top Android, iOS, and web engineers to bu...",BA/BS degree in Computer Science or equivalent practical experienc...,"Experience as a software developer, architect, technology advocate...",82,27,35
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",Plan requirements with internal customers.\nProvide portfolio repo...,BA/BS degree or equivalent practical experience.\n4 years of exper...,CTS Certification.\nExperience in the construction sector.\nExperi...,99,31,41
6,Google,"Supplier Development Engineer, Camera, Consumer Hardware",Hardware Engineering,"Mountain View, CA, United States",Manage cross-functional activities in the supply chain for overall...,BS degree in Engineering or equivalent practical experience.\n10 y...,Master's degree.\nExperience in the development of camera module i...,79,25,45
7,Google,"Strategic Technology Partner Manager, Healthcare and Life Sciences",Partnerships,"Sunnyvale, CA, United States",Lead the development and strategy with partners for healthcare and...,BA/BS degree or equivalent practical experience.\n5 years of exper...,"BA/BS degree in a technical, life sciences or engineering field or...",131,43,78
10,Google,"Data Analyst, Consumer Hardware",Product & Customer Support,"Mountain View, CA, United States",Build and maintain the Support Operations Analytics infrastructure...,"BA/BS degree in Computer Science, Engineering, Economics, Business...","Experience in designing and executing structured analysis, derivin...",70,43,91

Pre-process

In [13]:
gged = ggms.copy() #copy to edit

In [14]:
gged.head()

,Company,Title,Category,Location,Responsibilities,Minimum Qualifications,Preferred Qualifications,r_count,m_count,p_count
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States","Work one-on-one with the top Android, iOS, and web engineers to bu...",BA/BS degree in Computer Science or equivalent practical experienc...,"Experience as a software developer, architect, technology advocate...",82,27,35
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",Plan requirements with internal customers.\nProvide portfolio repo...,BA/BS degree or equivalent practical experience.\n4 years of exper...,CTS Certification.\nExperience in the construction sector.\nExperi...,99,31,41
6,Google,"Supplier Development Engineer, Camera, Consumer Hardware",Hardware Engineering,"Mountain View, CA, United States",Manage cross-functional activities in the supply chain for overall...,BS degree in Engineering or equivalent practical experience.\n10 y...,Master's degree.\nExperience in the development of camera module i...,79,25,45
7,Google,"Strategic Technology Partner Manager, Healthcare and Life Sciences",Partnerships,"Sunnyvale, CA, United States",Lead the development and strategy with partners for healthcare and...,BA/BS degree or equivalent practical experience.\n5 years of exper...,"BA/BS degree in a technical, life sciences or engineering field or...",131,43,78
10,Google,"Data Analyst, Consumer Hardware",Product & Customer Support,"Mountain View, CA, United States",Build and maintain the Support Operations Analytics infrastructure...,"BA/BS degree in Computer Science, Engineering, Economics, Business...","Experience in designing and executing structured analysis, derivin...",70,43,91

In [15]:
gged['Responsibilities'] = gged['Responsibilities'].apply(lambda x:
                                                          " ".join(x.lower()
                                                          for x in str(x).split()))
gged['Responsibilities'].head()

3     work one-on-one with the top android, ios, and web engineers to bu...
4     plan requirements with internal customers. provide portfolio repor...
6     manage cross-functional activities in the supply chain for overall...
7     lead the development and strategy with partners for healthcare and...
10    build and maintain the support operations analytics infrastructure...
Name: Responsibilities, dtype: object

In [16]:
gged['Responsibilities'] = gged['Responsibilities'].str.replace('[^\w\s]', ' ')

gged['Responsibilities'].head()

3     work one on one with the top android  ios  and web engineers to bu...
4     plan requirements with internal customers  provide portfolio repor...
6     manage cross functional activities in the supply chain for overall...
7     lead the development and strategy with partners for healthcare and...
10    build and maintain the support operations analytics infrastructure...
Name: Responsibilities, dtype: object

In [17]:
from nltk.corpus import stopwords

In [18]:
stop = stopwords.words('english')

gged['Responsibilities'] = gged['Responsibilities'].apply(lambda x:
                                                          " ".join(x for x in str(x).split()
                                                          if x not in stop))
gged['Responsibilities'].head()

3     work one one top android ios web engineers build exciting new prod...
4     plan requirements internal customers provide portfolio reports for...
6     manage cross functional activities supply chain overall technical ...
7     lead development strategy partners healthcare life sciences build ...
10    build maintain support operations analytics infrastructure customi...
Name: Responsibilities, dtype: object

In [19]:
freq_words = pd.Series(' '.join(gged['Responsibilities']).split()).value_counts()[:10]

freq_words

business      341
google        249
product       241
develop       229
teams         227
manage        216
team          212
work          199
management    164
support       160
dtype: int64

In [20]:
rare_words = pd.Series(' '.join(gged['Responsibilities']).split()).value_counts()

rare_words.count()

2730

In [21]:
rare_words = rare_words[rare_words == 1]

rare_words.count()

969

Filter out rare words

In [22]:
rare_words = list(rare_words.index)

gged['Responsibilities'] = gged['Responsibilities'].apply(lambda x:
                                                          " ".join(x for x in x.split()
                                                          if x not in rare_words))
gged['Responsibilities'].head(20)

3     work one one top android ios web engineers build new product api i...
4     plan requirements internal customers provide portfolio reports for...
6     manage cross functional activities supply chain overall technical ...
7     lead development strategy partners healthcare life sciences build ...
10    build maintain support operations analytics infrastructure customi...
19    plan coordinate deliver platforms hardware products lead creating ...
23    develop track core metrics across google cloud products including ...
24    manage global team technical trainers grow team achieve staffing g...
27    understand supply chain data structure critical data elements brid...
33    develop key performance indicators kpi dashboard competitive insig...
37    coordinate facilitate internal teams gain feedback insight agreeme...
41    help compile customer requirements well survey existing customer l...
42    provide program management support google cloud online experience ...
49    support operations projects related capacity planning allocation f...
56    serve point contact partners manage consistent operationally effic...
61    build consistent offerings energize market ecosystem partner googl...
74    design compelling portfolio technical trainings tools resources in...
81    create automation tools cadence concept allegro using cadence skil...
82    manage team program managers technical program managers lead proje...
87    build collaboration corporate engineering google cloud product are...
Name: Responsibilities, dtype: object

Lemmatization

In [23]:
from textblob import Word

In [24]:
gged['Responsibilities'] = gged['Responsibilities'].apply(lambda x:
                                                          " ".join([Word(word).lemmatize()
                                                          for word in x.split()]))
gged['Responsibilities'].head(20)

3     work one one top android io web engineer build new product api int...
4     plan requirement internal customer provide portfolio report foreca...
6     manage cross functional activity supply chain overall technical op...
7     lead development strategy partner healthcare life science build re...
10    build maintain support operation analytics infrastructure customiz...
19    plan coordinate deliver platform hardware product lead creating ma...
23    develop track core metric across google cloud product including ov...
24    manage global team technical trainer grow team achieve staffing go...
27    understand supply chain data structure critical data element bridg...
33    develop key performance indicator kpi dashboard competitive insigh...
37    coordinate facilitate internal team gain feedback insight agreemen...
41    help compile customer requirement well survey existing customer la...
42    provide program management support google cloud online experience ...
49    support operation project related capacity planning allocation ful...
56    serve point contact partner manage consistent operationally effici...
61    build consistent offering energize market ecosystem partner google...
74    design compelling portfolio technical training tool resource incen...
81    create automation tool cadence concept allegro using cadence skill...
82    manage team program manager technical program manager lead project...
87    build collaboration corporate engineering google cloud product are...
Name: Responsibilities, dtype: object

In [25]:
gged.head()

,Company,Title,Category,Location,Responsibilities,Minimum Qualifications,Preferred Qualifications,r_count,m_count,p_count
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States",work one one top android io web engineer build new product api int...,BA/BS degree in Computer Science or equivalent practical experienc...,"Experience as a software developer, architect, technology advocate...",82,27,35
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",plan requirement internal customer provide portfolio report foreca...,BA/BS degree or equivalent practical experience.\n4 years of exper...,CTS Certification.\nExperience in the construction sector.\nExperi...,99,31,41
6,Google,"Supplier Development Engineer, Camera, Consumer Hardware",Hardware Engineering,"Mountain View, CA, United States",manage cross functional activity supply chain overall technical op...,BS degree in Engineering or equivalent practical experience.\n10 y...,Master's degree.\nExperience in the development of camera module i...,79,25,45
7,Google,"Strategic Technology Partner Manager, Healthcare and Life Sciences",Partnerships,"Sunnyvale, CA, United States",lead development strategy partner healthcare life science build re...,BA/BS degree or equivalent practical experience.\n5 years of exper...,"BA/BS degree in a technical, life sciences or engineering field or...",131,43,78
10,Google,"Data Analyst, Consumer Hardware",Product & Customer Support,"Mountain View, CA, United States",build maintain support operation analytics infrastructure customiz...,"BA/BS degree in Computer Science, Engineering, Economics, Business...","Experience in designing and executing structured analysis, derivin...",70,43,91

Pre-process Minimum Qualification column

In [26]:
gged = gged.rename(columns={'Minimum Qualifications': 'mq'})

gged = gged.rename(columns={'Preferred Qualifications': 'pq'})

gged.head()

,Company,Title,Category,Location,Responsibilities,mq,pq,r_count,m_count,p_count
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States",work one one top android io web engineer build new product api int...,BA/BS degree in Computer Science or equivalent practical experienc...,"Experience as a software developer, architect, technology advocate...",82,27,35
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",plan requirement internal customer provide portfolio report foreca...,BA/BS degree or equivalent practical experience.\n4 years of exper...,CTS Certification.\nExperience in the construction sector.\nExperi...,99,31,41
6,Google,"Supplier Development Engineer, Camera, Consumer Hardware",Hardware Engineering,"Mountain View, CA, United States",manage cross functional activity supply chain overall technical op...,BS degree in Engineering or equivalent practical experience.\n10 y...,Master's degree.\nExperience in the development of camera module i...,79,25,45
7,Google,"Strategic Technology Partner Manager, Healthcare and Life Sciences",Partnerships,"Sunnyvale, CA, United States",lead development strategy partner healthcare life science build re...,BA/BS degree or equivalent practical experience.\n5 years of exper...,"BA/BS degree in a technical, life sciences or engineering field or...",131,43,78
10,Google,"Data Analyst, Consumer Hardware",Product & Customer Support,"Mountain View, CA, United States",build maintain support operation analytics infrastructure customiz...,"BA/BS degree in Computer Science, Engineering, Economics, Business...","Experience in designing and executing structured analysis, derivin...",70,43,91

In [27]:
gged['mq'].head()

3     BA/BS degree in Computer Science or equivalent practical experienc...
4     BA/BS degree or equivalent practical experience.\n4 years of exper...
6     BS degree in Engineering or equivalent practical experience.\n10 y...
7     BA/BS degree or equivalent practical experience.\n5 years of exper...
10    BA/BS degree in Computer Science, Engineering, Economics, Business...
Name: mq, dtype: object

In [28]:
gged['mq'] = gged['mq'].apply(lambda x: " ".join(x.lower()
                              for x in str(x).split()))
gged['mq'].head()

3     ba/bs degree in computer science or equivalent practical experienc...
4     ba/bs degree or equivalent practical experience. 4 years of experi...
6     bs degree in engineering or equivalent practical experience. 10 ye...
7     ba/bs degree or equivalent practical experience. 5 years of experi...
10    ba/bs degree in computer science, engineering, economics, business...
Name: mq, dtype: object

In [29]:
gged['mq'] = gged['mq'].str.replace('[^\w\s]', ' ')

gged['mq'].head()

3     ba bs degree in computer science or equivalent practical experienc...
4     ba bs degree or equivalent practical experience  4 years of experi...
6     bs degree in engineering or equivalent practical experience  10 ye...
7     ba bs degree or equivalent practical experience  5 years of experi...
10    ba bs degree in computer science  engineering  economics  business...
Name: mq, dtype: object

In [30]:
gged['mq'] = gged['mq'].apply(lambda x:
                              " ".join([Word(word).lemmatize(pos='v')
                              for word in x.split()]))
gged['mq'].head(20)

3     ba bs degree in computer science or equivalent practical experienc...
4     ba bs degree or equivalent practical experience 4 years of experie...
6     bs degree in engineer or equivalent practical experience 10 years ...
7     ba bs degree or equivalent practical experience 5 years of experie...
10    ba bs degree in computer science engineer economics business or a ...
19    bs degree in electrical engineer computer engineer computer scienc...
23    ba bs degree in a technical or quantitative business orient field ...
24    7 years of experience in a technical train role 5 years of experie...
27    5 years of experience in supply chain operations across technical ...
33    ba bs degree or equivalent practical experience 12 years of experi...
37    ba bs degree in business computer science or relate technology fie...
41    ba bs degree in computer science relate software engineer field or...
42    4 years of experience in program management work with design team ...
49    ba bs degree in engineer computer science or relate technical fiel...
56    bachelor s degree or equivalent practical experience 5 years of ex...
61    ba bs degree in computer science or software engineer or equivalen...
74    ba bs degree in computer science or software engineer or equivalen...
81    bachelor s degree in computer science electrical mechanical comput...
82    bs degree in engineer or it relate field or equivalent practical e...
87    bachelor s degree or equivalent practical experience 5 years of pa...
Name: mq, dtype: object

In [40]:
freq_mq = pd.Series(' '.join(gged['mq']).split()).value_counts()[:18]

freq_mq

experience    952
or            724
in            560
and           418
of            416
years         339
equivalent    326
degree        311
practical     301
bs            247
ba            231
a             218
with          211
management    157
work          155
the           130
to            108
field         105
dtype: int64

In [43]:
freq_mq = list(freq_mq.index)

In [46]:
gged['mq'] = gged['mq'].apply(lambda x: " ".join(x for x in x.split()
                              if x not in freq_mq))
gged['mq'].head()

3     computer science directly partner program one more follow language...
4     4 manage large scale global av deployments manage vendors deliver ...
6     engineer 10 design manufacture new product introduction npi role c...
7     5 partner business development public cloud solutions across softw...
10    computer science engineer economics business relate 4 an analytica...
Name: mq, dtype: object

In [47]:
rare_mq = pd.Series(' '.join(gged['mq']).split()).value_counts()

rare_mq = rare_mq[rare_mq == 1]

rare_mq.shape

(537,)

In [48]:
rare_mq.head()

respond         1
acquisitions    1
splunk          1
bsa             1
wire            1
dtype: int64

In [49]:
gged['mq'] = gged['mq'].apply(lambda x: " ".join(x for x in x.split()
                              if x not in rare_mq))
gged['mq'].head()

3     computer science directly partner program one more follow language...
4     4 manage large scale global deployments manage vendors deliver def...
6     engineer 10 design manufacture new product introduction npi role m...
7     5 partner business development public cloud solutions across softw...
10    computer science engineer economics business relate 4 an analytica...
Name: mq, dtype: object

In [52]:
gged['mq'] = gged['mq'].apply(lambda x: " ".join(x for x in x.split()
                              if x.isdigit() == False))

gged['mq'].head()

3     computer science directly partner program one more follow language...
4     manage large scale global deployments manage vendors deliver defin...
6     engineer design manufacture new product introduction npi role manu...
7     partner business development public cloud solutions across softwar...
10    computer science engineer economics business relate an analytical ...
Name: mq, dtype: object

In [54]:
tf_mq = (gged['mq']).apply(lambda x: 
                          pd.value_counts(x.split(" "))
                          ).sum(axis=0).reset_index()

tf_mq.columns = ['words','tf']

tf_mq.head()

         words    tf
0                3.0
1      ability  16.0
2         able  11.0
3      account  50.0
4  acquisition   2.0

In [56]:
for i,word in enumerate(tf_mq['words']):
    tf_mq.loc[i, 'idf'] = np.log(gged.shape[0]/
                        (len(gged[gged['mq'].str.contains(word)])))
tf_mq.head()

         words    tf       idf
0                3.0  0.000000
1      ability  16.0  2.847812
2         able  11.0  2.953173
3      account  50.0  2.129972
4  acquisition   2.0  5.150397

In [58]:
tf_mq['tfidf'] = tf_mq['tf'] * tf_mq['idf']

tf_mq.head()

         words    tf       idf       tfidf
0                3.0  0.000000    0.000000
1      ability  16.0  2.847812   45.564994
2         able  11.0  2.953173   32.484899
3      account  50.0  2.129972  106.498618
4  acquisition   2.0  5.150397   10.300794

In [59]:
type(tf_mq)

pandas.core.frame.DataFrame

In [61]:
mq_sorted = tf_mq.sort_values('tfidf', ascending=False)

mq_sorted.head(20)

           words    tf       idf       tfidf
346       market  77.0  1.873253  144.240443
167       design  73.0  1.931521  141.001063
573    technical  73.0  1.836211  134.043420
454      program  73.0  1.800493  131.436000
75      business  79.0  1.624037  128.298900
196     engineer  68.0  1.873253  127.381170
480       relate  89.0  1.400893  124.679491
170  development  61.0  1.951724  119.055171
483     relevant  81.0  1.449095  117.376716
510      science  66.0  1.766007  116.556460
118     computer  64.0  1.818193  116.364334
122      consult  63.0  1.732671  109.158245
151         data  54.0  2.014903  108.804763
3        account  50.0  2.129972  106.498618
66            be  44.0  2.347037  103.269622
456      project  40.0  2.409557   96.382289
575   technology  43.0  2.129972   91.588811
530     software  39.0  2.347037   91.534437
571         team  37.0  2.442347   90.366840
62      bachelor  43.0  2.082344   89.540805

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [64]:
mq_tfidf = TfidfVectorizer(max_features=1000, lowercase=True, analyzer='word',
                        stop_words = 'english', ngram_range=(1,1))
mq_train_vec = mq_tfidf.fit_transform(gged['mq'])

mq_train_vec

<345x568 sparse matrix of type '<class 'numpy.float64'>'
	with 4117 stored elements in Compressed Sparse Row format>

In [68]:
mq_tfidf.vocabulary_

{'computer': 102,
 'science': 468,
 'directly': 156,
 'partner': 369,
 'program': 414,
 'follow': 210,
 'languages': 292,
 'platforms': 390,
 'android': 24,
 'java': 280,
 'ios': 276,
 'javascript': 281,
 'manage': 312,
 'large': 293,
 'scale': 467,
 'global': 220,
 'deployments': 149,
 'vendors': 556,
 'deliver': 143,
 'define': 141,
 'project': 416,
 'audio': 45,
 'visual': 559,
 'design': 150,
 'integration': 262,
 'resolution': 450,
 'engineer': 177,
 'manufacture': 315,
 'new': 348,
 'product': 409,
 'introduction': 273,
 'npi': 352,
 'role': 458,
 'business': 61,
 'development': 153,
 'public': 418,
 'cloud': 79,
 'solutions': 489,
 'software': 488,
 'service': 477,
 'saas': 460,
 'platform': 389,
 'paas': 367,
 'infrastructure': 256,
 'iaas': 242,
 'market': 316,
 'technology': 531,
 'healthcare': 231,
 'industry': 254,
 'internal': 268,
 'customer': 130,
 'face': 198,
 'roles': 459,
 'economics': 166,
 'relate': 439,
 'analytical': 21,
 'intelligence': 263,
 'data': 134,
 'analytics': 22,
 'statistical': 506,
 'consult': 106,
 'sql': 495,
 'visualization': 560,
 'tool': 535,
 'tableau': 520,
 'electrical': 170,
 'asic': 39,
 'hardware': 229,
 'systems': 519,
 'cross': 122,
 'functional': 215,
 'organizational': 364,
 'context': 109,
 'technical': 529,
 'quantitative': 427,
 'orient': 366,
 'research': 449,
 'survey': 518,
 'multiple': 343,
 'support': 517,
 'operational': 356,
 'areas': 35,
 'lead': 296,
 'initiatives': 257,
 'include': 250,
 'blend': 57,
 'insights': 259,
 'measure': 322,
 'success': 515,
 'use': 548,
 'satisfaction': 466,
 'metrics': 333,
 'write': 566,
 'query': 429,
 'analysis': 19,
 'spss': 494,
 'python': 423,
 'principles': 403,
 'experiment': 193,
 'clickstream': 77,
 'qualitative': 425,
 'train': 537,
 'team': 527,
 'supply': 516,
 'chain': 70,
 'operations': 357,
 'network': 347,
 'strategy': 512,
 'stakeholder': 498,
 'finance': 201,
 'year': 567,
 'process': 406,
 'compute': 101,
 'environment': 181,
 'storage': 509,
 'life': 303,
 'deploy': 147,
 'sciences': 469,
 'similar': 482,
 'create': 119,
 'implement': 246,
 'complex': 97,
 'organizations': 365,
 'bachelor': 51,
 'channel': 72,
 'sales': 461,
 'company': 92,
 'build': 60,
 'model': 337,
 'programmatic': 415,
 'resources': 451,
 'mechanical': 324,
 'skill': 484,
 'developer': 152,
 'application': 29,
 'script': 471,
 'extraction': 197,
 'flow': 207,
 'automation': 49,
 'medium': 326,
 'enterprise': 180,
 'implementation': 247,
 'methodologies': 331,
 'soc': 485,
 'people': 376,
 'leadership': 298,
 'vendor': 555,
 'ip': 277,
 'analog': 17,
 'commodity': 88,
 'strategic': 510,
 'source': 490,
 'cost': 116,
 'integrate': 261,
 'circuit': 76,
 'analyze': 23,
 'trend': 543,
 'assess': 40,
 'opportunities': 358,
 'risk': 457,
 'early': 165,
 'stage': 497,
 'consumer': 107,
 'electronics': 171,
 'space': 492,
 'ms': 342,
 'chemistry': 73,
 'materials': 318,
 'quality': 426,
 'reliability': 443,
 'discipline': 157,
 'components': 99,
 'focus': 209,
 'mobile': 336,
 'interface': 266,
 'definitions': 142,
 'memory': 328,
 'interfaces': 267,
 'ability': 0,
 'travel': 541,
 'internationally': 269,
 'time': 534,
 'security': 473,
 'optimization': 359,
 'windows': 565,
 'r2': 431,
 'operate': 355,
 'perl': 379,
 'shell': 480,
 'language': 291,
 'report': 446,
 'dashboarding': 133,
 'professional': 412,
 'app': 28,
 'information': 255,
 'license': 302,
 'structure': 513,
 'contract': 111,
 'improvement': 248,
 'party': 371,
 'methods': 332,
 'sample': 463,
 'control': 112,
 'production': 410,
 'drive': 163,
 'purpose': 421,
 'applications': 30,
 'publish': 419,
 'ee': 169,
 'performance': 377,
 'relevant': 442,
 'databases': 136,
 'repeatable': 445,
 'analyse': 18,
 'mba': 321,
 'graduate': 225,
 'corporate': 115,
 'collaborate': 84,
 'present': 402,
 'executives': 191,
 'communicate': 89,
 'highly': 235,
 'technologies': 530,
 'products': 411,
 'landscape': 290,
 'mathematics': 319,
 'statistics': 507,
 'manager': 313,
 'administration': 5,
 'sap': 464,
 'plan': 388,
 'hyperion': 241,
 'financial': 202,
 'hfm': 233,
 'etl': 186,
 'creative': 120,
 'agency': 12,
 'house': 236,
 'campaign': 65,
 'capacity': 66,
 'independent': 252,
 'vend': 554,
 'isv': 278,
 'topics': 536,
 'stakeholders': 499,
 'competitive': 94,
 'dynamics': 164,
 'buy': 62,
 'behavior': 56,
 'online': 354,
 'web': 562,
 'documentation': 160,
 'journalism': 283,
 'code': 82,
 'legal': 300,
 'authorization': 47,
 'unite': 545,
 'state': 505,
 'physical': 385,
 'digital': 154,
 'formal': 212,
 'verification': 557,
 'power': 398,
 'able': 1,
 'start': 503,
 'deployment': 148,
 'environments': 182,
 'delivery': 144,
 'pdm': 375,
 'perspective': 381,
 'package': 368,
 'commodities': 87,
 'print': 404,
 'injection': 258,
 'mold': 338,
 'procurement': 408,
 'identify': 244,
 'recruit': 434,
 'strategies': 511,
 'america': 15,
 'investment': 275,
 'bank': 52,
 'media': 325,
 'database': 135,
 'standard': 501,
 'practice': 400,
 'key': 286,
 'standards': 502,
 'display': 158,
 'equipment': 183,
 'nan': 345,
 'logistics': 308,
 'domestically': 161,
 'agreement': 13,
 'base': 54,
 'require': 447,
 'internet': 270,
 'client': 78,
 'direct': 155,
 'engagement': 176,
 'account': 2,
 'capital': 67,
 'sit': 483,
 'salesforce': 462,
 'administrator': 6,
 'function': 214,
 'industrial': 253,
 'high': 234,
 'volume': 561,
 'core': 114,
 'machine': 310,
 'draw': 162,
 'fixture': 205,
 'qualification': 424,
 'measurement': 323,
 'customize': 131,
 'custom': 129,
 'cycle': 132,
 'test': 533,
 'treasury': 542,
 'procure': 407,
 'pay': 372,
 'b2b': 50,
 'budget': 59,
 'payroll': 374,
 'order': 362,
 'cash': 68,
 'end': 175,
 'html5': 239,
 'css': 124,
 'motion': 341,
 'socs': 487,
 'assistive': 42,
 'screen': 470,
 'physics': 386,
 'register': 436,
 'level': 301,
 'relationships': 441,
 'sell': 474,
 'coach': 80,
 'mentor': 329,
 'executive': 190,
 'develop': 151,
 'agreements': 14,
 'conduct': 104,
 'content': 108,
 'partnerships': 370,
 'advertise': 9,
 'game': 218,
 'retail': 455,
 'editorial': 168,
 'learn': 299,
 'members': 327,
 'tech': 528,
 'apply': 31,
 'social': 486,
 'coursework': 117,
 'nature': 346,
 'datasets': 137,
 'html': 238,
 'api': 27,
 'php': 384,
 'mysql': 344,
 'flat': 206,
 'file': 200,
 'handle': 228,
 'google': 222,
 'tag': 521,
 'tealium': 526,
 'adobe': 8,
 'activation': 4,
 'qubit': 428,
 'experimentation': 195,
 'optimize': 360,
 'target': 523,
 'optimizely': 361,
 'acquisition': 3,
 'apps': 32,
 'frameworks': 213,
 'websites': 563,
 'phase': 382,
 'user': 549,
 'external': 196,
 'commerce': 86,
 'merchandise': 330,
 'pr': 399,
 'communications': 91,
 'pursue': 422,
 'expect': 192,
 'graduation': 226,
 'date': 138,
 'december': 140,
 'june': 285,
 'complete': 95,
 'week': 564,
 'begin': 55,
 'journalists': 284,
 'government': 223,
 'non': 349,
 'profit': 413,
 'responsibilities': 452,
 'com': 85,
 'execution': 189,
 'users': 550,
 'requirements': 448,
 'search': 472,
 'speak': 493,
 'english': 178,
 'fluently': 208,
 'idiomatically': 245,
 'event': 187,
 'staff': 496,
 'assets': 41,
 'currently': 127,
 'enrol': 179,
 'major': 311,
 'university': 546,
 'political': 393,
 'position': 395,
 'experimental': 194,
 'sas': 465,
 'associate': 43,
 'email': 172,
 'iterative': 279,
 'emphasis': 173,
 'firm': 203,
 'portfolio': 394,
 'mix': 335,
 'limit': 304,
 'brand': 58,
 'ux': 553,
 'conceptualize': 103,
 'nonprofit': 350,
 'settings': 479,
 'change': 71,
 'affect': 10,
 'short': 481,
 'long': 309,
 'form': 211,
 'post': 396,
 'senior': 476,
 'cs': 123,
 'hci': 230,
 'cognitive': 83,
 'psychology': 417,
 'copywriting': 113,
 'kpis': 287,
 'pre': 401,
 'execute': 188,
 'notification': 351,
 'policy': 392,
 'document': 159,
 'human': 240,
 'interaction': 265,
 'return': 456,
 'completion': 96,
 'internship': 271,
 'set': 478,
 'manipulation': 314,
 'computational': 100,
 'matlab': 320,
 'anthropology': 26,
 'factor': 199,
 'semi': 475,
 'interview': 272,
 'contextual': 110,
 'visit': 558,
 'usability': 547,
 'study': 514,
 'live': 306,
 'remote': 444,
 'userzoom': 552,
 'usertesting': 551,
 'communication': 90,
 'graphic': 227,
 'demonstrate': 145,
 'culture': 126,
 'object': 353,
 'latest': 294,
 'css3': 125,
 'uis': 544,
 'master': 317,
 'phd': 383,
 'range': 432,
 'private': 405,
 'equity': 184,
 'stata': 504,
 'articulate': 37,
 'question': 430,
 'pull': 420,
 'arrive': 36,
 'answer': 25,
 'ce': 69,
 'telecoms': 532,
 'line': 305,
 'plm': 391,
 'cad': 64,
 'interact': 264,
 'area': 34,
 'attendance': 44,
 'compensation': 93,
 'audit': 46,
 'cpa': 118,
 'ca': 63,
 'gaap': 217,
 'tax': 524,
 'fx': 216,
 'hedge': 232,
 'transactions': 539,
 'asc': 38,
 'sox': 491,
 'icfr': 243,
 'payments': 373,
 'money': 339,
 'transmitter': 540,
 'aml': 16,
 'regulations': 437,
 'fix': 204,
 'income': 251,
 'grade': 224,
 'compliance': 98,
 'kyc': 288,
 'investigations': 274,
 'organization': 363,
 'institution': 260,
 'hr': 237,
 'credit': 121,
 'improvements': 249,
 'department': 146,
 'analyst': 20,
 'construction': 105,
 'cod': 81,
 'law': 295,
 'jd': 282,
 'admit': 7,
 'bar': 53,
 'locate': 307,
 'good': 221,
 'stand': 500,
 'authorize': 48,
 'status': 508,
 'regulatory': 438,
 'transactional': 538,
 'responsibility': 453,
 'result': 454,
 'minimum': 334,
 'child': 74,
 'permit': 380,
 'children': 75,
 'age': 11,
 'months': 340,
 'teachers': 525,
 'curriculum': 128,
 'day': 139,
 'pick': 387,
 'periods': 378,
 'recruitment': 435,
 'talent': 522,
 'employee': 174,
 'relations': 440,
 'generalist': 219,
 'leaders': 297,
 'real': 433,
 'estate': 185,
 'architecture': 33,
 'land': 289,
 'potentially': 397,
 'ecosystems': 167}

In [76]:
idf = mq_tfidf.idf_

print(dict(zip(mq_tfidf.get_feature_names(), idf)))

{'ability': 4.0132254310015085, 'able': 4.448543502259353, 'account': 3.108769156774356, 'acquisition': 5.747826486389615, 'activation': 5.747826486389615, 'administration': 4.90052862600241, 'administrator': 5.747826486389615, 'admit': 4.90052862600241, 'adobe': 5.460144413937834, 'advertise': 5.747826486389615, 'affect': 5.747826486389615, 'age': 6.153291594497779, 'agency': 4.649214197721505, 'agreement': 5.460144413937834, 'agreements': 5.747826486389615, 'america': 6.153291594497779, 'aml': 5.460144413937834, 'analog': 5.747826486389615, 'analyse': 5.460144413937834, 'analysis': 3.9560670171615597, 'analyst': 5.747826486389615, 'analytical': 4.073850052817943, 'analytics': 4.0132254310015085, 'analyze': 4.543853682063679, 'android': 5.460144413937834, 'answer': 5.460144413937834, 'anthropology': 5.237000862623624, 'api': 6.153291594497779, 'app': 5.460144413937834, 'application': 5.054679305829669, 'applications': 4.543853682063679, 'apply': 5.054679305829669, 'apps': 5.747826486389615, 'architecture': 5.747826486389615, 'area': 5.237000862623624, 'areas': 4.543853682063679, 'arrive': 5.460144413937834, 'articulate': 5.747826486389615, 'asc': 6.153291594497779, 'asic': 5.460144413937834, 'assess': 5.460144413937834, 'assets': 4.7669972333778885, 'assistive': 6.153291594497779, 'associate': 5.747826486389615, 'attendance': 5.747826486389615, 'audio': 5.747826486389615, 'audit': 4.649214197721505, 'authorization': 4.361532125269724, 'authorize': 4.90052862600241, 'automation': 5.460144413937834, 'b2b': 5.460144413937834, 'bachelor': 3.0622491411394632, 'bank': 4.073850052817943, 'bar': 4.90052862600241, 'base': 4.90052862600241, 'begin': 4.7669972333778885, 'behavior': 5.747826486389615, 'blend': 5.747826486389615, 'brand': 5.237000862623624, 'budget': 5.747826486389615, 'build': 3.755396321699408, 'business': 2.612332270460465, 'buy': 5.747826486389615, 'ca': 4.448543502259353, 'cad': 6.153291594497779, 'campaign': 4.649214197721505, 'capacity': 4.90052862600241, 'capital': 5.747826486389615, 'cash': 5.747826486389615, 'ce': 5.747826486389615, 'chain': 4.649214197721505, 'change': 5.054679305829669, 'channel': 4.448543502259353, 'chemistry': 5.747826486389615, 'child': 6.153291594497779, 'children': 6.153291594497779, 'circuit': 5.747826486389615, 'clickstream': 5.747826486389615, 'client': 4.649214197721505, 'cloud': 3.8019163373343012, 'coach': 5.237000862623624, 'cod': 5.747826486389615, 'code': 5.237000862623624, 'cognitive': 5.460144413937834, 'collaborate': 5.237000862623624, 'com': 5.237000862623624, 'commerce': 5.237000862623624, 'commodities': 5.747826486389615, 'commodity': 5.747826486389615, 'communicate': 5.747826486389615, 'communication': 5.054679305829669, 'communications': 3.9019997958912835, 'company': 3.7109445591285746, 'compensation': 5.237000862623624, 'competitive': 5.747826486389615, 'complete': 4.7669972333778885, 'completion': 5.054679305829669, 'complex': 4.543853682063679, 'compliance': 5.460144413937834, 'components': 5.747826486389615, 'computational': 5.460144413937834, 'compute': 5.054679305829669, 'computer': 2.8033875072231744, 'conceptualize': 5.460144413937834, 'conduct': 4.90052862600241, 'construction': 5.460144413937834, 'consult': 2.719304390012633, 'consumer': 4.361532125269724, 'content': 4.2814894175961875, 'context': 5.747826486389615, 'contextual': 5.460144413937834, 'contract': 5.237000862623624, 'control': 5.237000862623624, 'copywriting': 5.747826486389615, 'core': 5.460144413937834, 'corporate': 3.2355208624135, 'cost': 5.747826486389615, 'coursework': 5.747826486389615, 'cpa': 4.138388573955514, 'create': 4.90052862600241, 'creative': 4.448543502259353, 'credit': 5.460144413937834, 'cross': 4.361532125269724, 'cs': 5.460144413937834, 'css': 5.460144413937834, 'css3': 5.460144413937834, 'culture': 5.747826486389615, 'currently': 4.543853682063679, 'curriculum': 6.153291594497779, 'custom': 5.747826486389615, 'customer': 4.2814894175961875, 'customize': 5.237000862623624, 'cycle': 5.237000862623624, 'dashboarding': 5.747826486389615, 'data': 3.1328667083534163, 'database': 4.649214197721505, 'databases': 5.054679305829669, 'datasets': 5.237000862623624, 'date': 4.7669972333778885, 'day': 6.153291594497779, 'december': 4.7669972333778885, 'define': 5.747826486389615, 'definitions': 5.747826486389615, 'deliver': 4.7669972333778885, 'delivery': 5.460144413937834, 'demonstrate': 5.747826486389615, 'department': 5.237000862623624, 'deploy': 5.747826486389615, 'deployment': 5.460144413937834, 'deployments': 5.747826486389615, 'design': 2.9146131423333985, 'develop': 4.207381445442466, 'developer': 5.747826486389615, 'development': 2.9344157696295783, 'digital': 4.448543502259353, 'direct': 4.90052862600241, 'directly': 5.460144413937834, 'discipline': 4.90052862600241, 'display': 5.460144413937834, 'document': 5.747826486389615, 'documentation': 5.747826486389615, 'domestically': 5.460144413937834, 'draw': 5.747826486389615, 'drive': 4.7669972333778885, 'dynamics': 5.460144413937834, 'early': 5.460144413937834, 'economics': 4.207381445442466, 'ecosystems': 5.747826486389615, 'editorial': 5.054679305829669, 'ee': 5.747826486389615, 'electrical': 4.543853682063679, 'electronics': 4.7669972333778885, 'email': 5.460144413937834, 'emphasis': 5.237000862623624, 'employee': 5.747826486389615, 'end': 5.237000862623624, 'engagement': 5.054679305829669, 'engineer': 2.85745472849345, 'english': 5.460144413937834, 'enrol': 4.543853682063679, 'enterprise': 3.8019163373343012, 'environment': 4.073850052817943, 'environments': 5.460144413937834, 'equipment': 5.460144413937834, 'equity': 5.460144413937834, 'estate': 5.237000862623624, 'etl': 5.460144413937834, 'event': 4.90052862600241, 'execute': 5.460144413937834, 'execution': 5.054679305829669, 'executive': 4.543853682063679, 'executives': 5.237000862623624, 'expect': 4.7669972333778885, 'experiment': 5.237000862623624, 'experimental': 5.460144413937834, 'experimentation': 5.460144413937834, 'external': 5.460144413937834, 'extraction': 5.747826486389615, 'face': 4.649214197721505, 'factor': 5.460144413937834, 'file': 5.460144413937834, 'finance': 3.2910907135683107, 'financial': 4.543853682063679, 'firm': 4.0132254310015085, 'fix': 5.460144413937834, 'fixture': 5.747826486389615, 'flat': 5.747826486389615, 'flow': 5.237000862623624, 'fluently': 5.747826486389615, 'focus': 4.0132254310015085, 'follow': 4.2814894175961875, 'form': 5.747826486389615, 'formal': 5.747826486389615, 'frameworks': 6.153291594497779, 'function': 5.054679305829669, 'functional': 4.073850052817943, 'fx': 5.747826486389615, 'gaap': 5.460144413937834, 'game': 5.747826486389615, 'generalist': 5.460144413937834, 'global': 4.448543502259353, 'good': 4.90052862600241, 'google': 5.237000862623624, 'government': 5.237000862623624, 'grade': 5.460144413937834, 'graduate': 4.7669972333778885, 'graduation': 4.7669972333778885, 'graphic': 5.460144413937834, 'handle': 5.747826486389615, 'hardware': 4.649214197721505, 'hci': 4.448543502259353, 'healthcare': 5.460144413937834, 'hedge': 5.747826486389615, 'hfm': 5.747826486389615, 'high': 4.207381445442466, 'highly': 5.747826486389615, 'house': 4.138388573955514, 'hr': 4.543853682063679, 'html': 5.237000862623624, 'html5': 5.237000862623624, 'human': 4.361532125269724, 'hyperion': 6.153291594497779, 'iaas': 5.237000862623624, 'icfr': 5.747826486389615, 'identify': 5.747826486389615, 'idiomatically': 5.747826486389615, 'implement': 4.073850052817943, 'implementation': 4.361532125269724, 'improvement': 5.237000862623624, 'improvements': 5.747826486389615, 'include': 3.445241393395569, 'income': 5.747826486389615, 'independent': 5.747826486389615, 'industrial': 4.90052862600241, 'industry': 3.2629198366016143, 'information': 4.543853682063679, 'infrastructure': 4.448543502259353, 'initiatives': 5.054679305829669, 'injection': 5.747826486389615, 'insights': 5.054679305829669, 'institution': 6.153291594497779, 'integrate': 5.460144413937834, 'integration': 4.649214197721505, 'intelligence': 4.7669972333778885, 'interact': 5.747826486389615, 'interaction': 4.543853682063679, 'interface': 5.747826486389615, 'interfaces': 5.747826486389615, 'internal': 4.2814894175961875, 'internationally': 4.90052862600241, 'internet': 5.747826486389615, 'internship': 4.90052862600241, 'interview': 5.460144413937834, 'introduction': 5.747826486389615, 'investigations': 5.747826486389615, 'investment': 4.0132254310015085, 'ios': 5.747826486389615, 'ip': 5.747826486389615, 'isv': 5.747826486389615, 'iterative': 5.747826486389615, 'java': 4.361532125269724, 'javascript': 4.448543502259353, 'jd': 5.054679305829669, 'journalism': 4.90052862600241, 'journalists': 5.747826486389615, 'june': 4.7669972333778885, 'key': 5.747826486389615, 'kpis': 5.747826486389615, 'kyc': 5.747826486389615, 'land': 5.747826486389615, 'landscape': 5.747826486389615, 'language': 5.054679305829669, 'languages': 4.138388573955514, 'large': 4.543853682063679, 'latest': 5.747826486389615, 'law': 4.649214197721505, 'lead': 3.8019163373343012, 'leaders': 5.747826486389615, 'leadership': 4.649214197721505, 'learn': 5.237000862623624, 'legal': 5.747826486389615, 'level': 5.237000862623624, 'license': 5.460144413937834, 'life': 5.237000862623624, 'limit': 5.747826486389615, 'line': 5.747826486389615, 'live': 5.460144413937834, 'locate': 4.90052862600241, 'logistics': 5.747826486389615, 'long': 5.747826486389615, 'machine': 5.460144413937834, 'major': 5.237000862623624, 'manage': 3.47914294507125, 'manager': 4.7669972333778885, 'manipulation': 5.747826486389615, 'manufacture': 4.649214197721505, 'market': 2.85745472849345, 'master': 4.90052862600241, 'materials': 5.460144413937834, 'mathematics': 4.2814894175961875, 'matlab': 4.90052862600241, 'mba': 4.649214197721505, 'measure': 5.747826486389615, 'measurement': 6.153291594497779, 'mechanical': 5.237000862623624, 'media': 4.073850052817943, 'medium': 5.460144413937834, 'members': 5.460144413937834, 'memory': 5.747826486389615, 'mentor': 5.747826486389615, 'merchandise': 5.237000862623624, 'methodologies': 5.747826486389615, 'methods': 5.460144413937834, 'metrics': 5.747826486389615, 'minimum': 6.153291594497779, 'mix': 5.747826486389615, 'mobile': 4.361532125269724, 'model': 4.2814894175961875, 'mold': 5.747826486389615, 'money': 5.747826486389615, 'months': 5.747826486389615, 'motion': 5.747826486389615, 'ms': 5.054679305829669, 'multiple': 5.054679305829669, 'mysql': 5.460144413937834, 'nan': 5.460144413937834, 'nature': 5.747826486389615, 'network': 5.054679305829669, 'new': 4.90052862600241, 'non': 5.237000862623624, 'nonprofit': 5.747826486389615, 'notification': 5.747826486389615, 'npi': 5.460144413937834, 'object': 5.747826486389615, 'online': 4.90052862600241, 'operate': 5.237000862623624, 'operational': 4.543853682063679, 'operations': 3.412451570572578, 'opportunities': 5.747826486389615, 'optimization': 5.460144413937834, 'optimize': 5.237000862623624, 'optimizely': 5.460144413937834, 'order': 5.460144413937834, 'organization': 4.90052862600241, 'organizational': 5.747826486389615, 'organizations': 5.460144413937834, 'orient': 5.054679305829669, 'paas': 5.054679305829669, 'package': 5.237000862623624, 'partner': 3.6275629501895237, 'partnerships': 5.460144413937834, 'party': 5.460144413937834, 'pay': 5.237000862623624, 'payments': 5.460144413937834, 'payroll': 5.237000862623624, 'pdm': 5.747826486389615, 'people': 4.138388573955514, 'performance': 5.460144413937834, 'periods': 6.153291594497779, 'perl': 5.747826486389615, 'permit': 6.153291594497779, 'perspective': 5.747826486389615, 'phase': 5.460144413937834, 'phd': 5.747826486389615, 'php': 5.747826486389615, 'physical': 5.460144413937834, 'physics': 4.90052862600241, 'pick': 6.153291594497779, 'plan': 3.8507065015037334, 'platform': 5.237000862623624, 'platforms': 4.448543502259353, 'plm': 6.153291594497779, 'policy': 5.747826486389615, 'political': 5.237000862623624, 'portfolio': 4.543853682063679, 'position': 4.90052862600241, 'post': 5.460144413937834, 'potentially': 5.747826486389615, 'power': 5.747826486389615, 'pr': 4.649214197721505, 'practice': 4.649214197721505, 'pre': 5.460144413937834, 'present': 5.237000862623624, 'principles': 4.90052862600241, 'print': 5.747826486389615, 'private': 5.460144413937834, 'process': 3.588342237036242, 'procure': 5.460144413937834, 'procurement': 5.747826486389615, 'product': 3.6683849447097785, 'production': 4.649214197721505, 'products': 4.361532125269724, 'professional': 4.361532125269724, 'profit': 5.747826486389615, 'program': 2.821087084322575, 'programmatic': 5.460144413937834, 'project': 3.3807028722579977, 'psychology': 4.543853682063679, 'public': 4.073850052817943, 'publish': 5.460144413937834, 'pull': 5.460144413937834, 'purpose': 5.747826486389615, 'pursue': 4.543853682063679, 'python': 3.8019163373343012, 'qualification': 5.237000862623624, 'qualitative': 5.460144413937834, 'quality': 5.460144413937834, 'quantitative': 3.755396321699408, 'qubit': 5.747826486389615, 'query': 4.649214197721505, 'question': 5.747826486389615, 'r2': 6.153291594497779, 'range': 5.747826486389615, 'real': 5.237000862623624, 'recruit': 4.90052862600241, 'recruitment': 5.460144413937834, 'register': 4.7669972333778885, 'regulations': 5.460144413937834, 'regulatory': 6.153291594497779, 'relate': 2.3920914788042165, 'relations': 5.747826486389615, 'relationships': 5.054679305829669, 'relevant': 2.4397195277934713, 'reliability': 5.747826486389615, 'remote': 5.460144413937834, 'repeatable': 5.747826486389615, 'report': 4.90052862600241, 'require': 5.460144413937834, 'requirements': 5.460144413937834, 'research': 4.2814894175961875, 'resolution': 5.747826486389615, 'resources': 5.747826486389615, 'responsibilities': 5.747826486389615, 'responsibility': 5.747826486389615, 'result': 5.747826486389615, 'retail': 5.237000862623624, 'return': 4.90052862600241, 'risk': 5.054679305829669, 'role': 3.0397762852874046, 'roles': 4.543853682063679, 'saas': 4.7669972333778885, 'sales': 3.445241393395569, 'salesforce': 5.747826486389615, 'sample': 5.460144413937834, 'sap': 5.747826486389615, 'sas': 5.054679305829669, 'satisfaction': 5.747826486389615, 'scale': 4.649214197721505, 'science': 2.7520942128356234, 'sciences': 5.237000862623624, 'screen': 5.747826486389615, 'script': 4.207381445442466, 'search': 5.237000862623624, 'security': 4.543853682063679, 'sell': 5.237000862623624, 'semi': 5.460144413937834, 'senior': 5.237000862623624, 'service': 4.207381445442466, 'set': 4.7669972333778885, 'settings': 5.747826486389615, 'shell': 5.747826486389615, 'short': 5.747826486389615, 'similar': 4.207381445442466, 'sit': 5.747826486389615, 'skill': 6.153291594497779, 'soc': 5.747826486389615, 'social': 5.747826486389615, 'socs': 5.747826486389615, 'software': 3.3200782504415627, 'solutions': 4.207381445442466, 'source': 5.054679305829669, 'sox': 5.460144413937834, 'space': 5.237000862623624, 'speak': 5.747826486389615, 'spss': 5.460144413937834, 'sql': 3.5142342648825204, 'staff': 5.237000862623624, 'stage': 5.747826486389615, 'stakeholder': 5.237000862623624, 'stakeholders': 5.054679305829669, 'stand': 4.7669972333778885, 'standard': 5.460144413937834, 'standards': 5.237000862623624, 'start': 5.747826486389615, 'stata': 5.460144413937834, 'state': 3.9560670171615597, 'statistical': 3.9019997958912835, 'statistics': 3.6683849447097785, 'status': 4.90052862600241, 'storage': 5.237000862623624, 'strategic': 4.361532125269724, 'strategies': 4.649214197721505, 'strategy': 3.588342237036242, 'structure': 5.237000862623624, 'study': 5.460144413937834, 'success': 5.747826486389615, 'supply': 4.543853682063679, 'support': 4.207381445442466, 'survey': 5.460144413937834, 'systems': 3.9560670171615597, 'tableau': 4.90052862600241, 'tag': 5.747826486389615, 'talent': 5.054679305829669, 'target': 5.460144413937834, 'tax': 5.747826486389615, 'teachers': 6.153291594497779, 'tealium': 5.747826486389615, 'team': 3.412451570572578, 'tech': 4.0132254310015085, 'technical': 2.821087084322575, 'technologies': 4.448543502259353, 'technology': 3.108769156774356, 'telecoms': 5.747826486389615, 'test': 4.649214197721505, 'time': 3.8507065015037334, 'tool': 3.9560670171615597, 'topics': 5.460144413937834, 'train': 4.649214197721505, 'transactional': 5.747826486389615, 'transactions': 5.747826486389615, 'transmitter': 5.747826486389615, 'travel': 4.207381445442466, 'treasury': 5.460144413937834, 'trend': 5.460144413937834, 'uis': 5.747826486389615, 'unite': 4.361532125269724, 'university': 5.460144413937834, 'usability': 5.460144413937834, 'use': 3.9019997958912835, 'user': 5.054679305829669, 'users': 6.153291594497779, 'usertesting': 5.460144413937834, 'userzoom': 5.460144413937834, 'ux': 4.7669972333778885, 'vend': 5.747826486389615, 'vendor': 4.7669972333778885, 'vendors': 5.460144413937834, 'verification': 5.747826486389615, 'visit': 5.460144413937834, 'visual': 4.90052862600241, 'visualization': 5.460144413937834, 'volume': 5.460144413937834, 'web': 4.073850052817943, 'websites': 5.460144413937834, 'week': 4.7669972333778885, 'windows': 6.153291594497779, 'write': 4.073850052817943, 'year': 4.448543502259353}

In [74]:
tf_mq[tf_mq['words'] == 'ability']

     words    tf       idf      tfidf
1  ability  16.0  2.847812  45.564994