In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_colwidth', -1)

In [3]:
borig = pd.read_csv('2018clean3.csv', header=0, index_col=0, dtype={'MainSic': object})

print(borig.shape)
borig.head(5)

(10772, 29)

,EmployerName,Address,CompanyNumber,SicCodes,DiffMeanHourlyPercent,DiffMedianHourlyPercent,DiffMeanBonusPercent,DiffMedianBonusPercent,MaleBonusPercent,FemaleBonusPercent,...,ResponsiblePerson,EmployerSize,CurrentName,SubmittedAfterTheDeadline,DueDate,DateSubmitted,Post,Val,MainSic,MainSection
0,"BRYANSTON SCHOOL,INCORPORATED","Bryanston House,\r\r\r\r\nBlandford,\r\r\r\r\nDorset,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nDT11 0PX",00226143,85310,19.6,32.5,NaN,NaN,0.0,0.0,...,Michael McGovern (Chief Operating Officer),500 to 999,"""Bryanston School"",Incorporated",False,05/04/2019 00:00:00,03/04/2019 13:43:34,DT11 0PX,True,85310,Education
1,"RED BAND CHEMICAL COMPANY, LIMITED","19 Smith's Place,\r\r\r\r\nLeith Walk,\r\r\r\r\nEdinburgh,\r\r\r\r\nEH6 8NU",SC016876,47730,7.7,-4.2,23.7,-75.2,22.2,82.0,...,Philip Galt (Managing Director),250 to 499,"""RED BAND"" CHEMICAL COMPANY, LIMITED",False,05/04/2019 00:00:00,01/04/2019 12:37:21,EH6 8NU,True,47730,Wholesale and retail trade; repair of motor vehicles and
2,118 LIMITED,"Fusion Point,\r\r\r\r\nDumballs Road,\r\r\r\r\nCardiff,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nCF10 5BF",03951948,61900,7.7,12.7,11.3,10.9,67.0,52.0,...,Michael Graham (CEO),1000 to 4999,118 LIMITED,False,05/04/2019 00:00:00,06/03/2019 13:26:24,CF10 5BF,True,61900,Information and communication
3,123 EMPLOYEES LTD,"34 Roundhay Road,\r\r\r\r\nLeeds,\r\r\r\r\nEngland,\r\r\r\r\nLS7 1AB",10530651,78300,30.0,29.0,-10.0,69.0,46.0,74.0,...,Chloe Lines (Financial Controller),250 to 499,123 EMPLOYEES LTD,False,05/04/2019 00:00:00,03/04/2019 15:43:17,LS7 1AB,True,78300,Administrative and support service activities
4,1509 GROUP,"Royal Grammar School, High Street,\r\r\r\r\nGuildford,\r\r\r\r\nSurrey,\r\r\r\r\nGU1 3BB",04104101,"85200,\r\r\r\r\n85310",13.4,12.7,0.0,0.0,0.0,0.0,...,Kate Perceval (Bursar),250 to 499,1509 GROUP,False,05/04/2019 00:00:00,18/03/2019 14:03:16,GU1 3BB,True,85200,Education

In [4]:
borig['MainSection'].value_counts()

Manufacturing                                               1385
Administrative and support service activities               1264
Education                                                   1223
Wholesale and retail trade; repair of motor vehicles and    1008
Human health and social work activities                     988
Professional, scientific and technical activities           714
Accommodation and food service activities                   563
Public administration and defence; compulsory social        473
Information and communication                               452
Financial and insurance activities                          414
Transportation and storage                                  399
Construction                                                329
Arts, entertainment and recreation                          295
Other service activities                                    218
Real estate activities                                      132
Water supply, sewerage, waste management and                70
Mining and Quarrying                                        59
Electricity, gas, steam and air conditioning supply         59
Agriculture, Forestry and Fishing                           48
Activities of extraterritorial organisations and            9
Activities of households as employers; undifferentiated     4
Name: MainSection, dtype: int64

In [5]:
SectionHourlySum = pd.pivot_table(borig, values='DiffMeanHourlyPercent',
                            index=['MainSection'], aggfunc=np.sum)
SectionHourlySum

                                                          DiffMeanHourlyPercent
MainSection
Accommodation and food service activities                 3901.1
Activities of extraterritorial organisations and          53.8
Activities of households as employers; undifferentiated  -1.5
Administrative and support service activities             13216.6
Agriculture, Forestry and Fishing                         703.9
Arts, entertainment and recreation                        5994.2
Construction                                              7296.5
Education                                                 19751.7
Electricity, gas, steam and air conditioning supply       889.4
Financial and insurance activities                        10999.5
Human health and social work activities                   10593.1
Information and communication                             8809.2
Manufacturing                                             17449.0
Mining and Quarrying                                      1306.4
Other service activities                                  2663.7
Professional, scientific and technical activities         13540.8
Public administration and defence; compulsory social      3689.1
Real estate activities                                    2219.2
Transportation and storage                                4302.8
Water supply, sewerage, waste management and              426.7
Wholesale and retail trade; repair of motor vehicles and  15062.1

In [6]:
SectionHourly = pd.pivot_table(borig, values='DiffMeanHourlyPercent',
                            index=['MainSection'], aggfunc=np.mean)
SectionHourly

                                                          DiffMeanHourlyPercent
MainSection
Accommodation and food service activities                 6.929130
Activities of extraterritorial organisations and          5.977778
Activities of households as employers; undifferentiated  -0.375000
Administrative and support service activities             10.456171
Agriculture, Forestry and Fishing                         14.664583
Arts, entertainment and recreation                        20.319322
Construction                                              22.177812
Education                                                 16.150204
Electricity, gas, steam and air conditioning supply       15.074576
Financial and insurance activities                        26.568841
Human health and social work activities                   10.721761
Information and communication                             19.489381
Manufacturing                                             12.598556
Mining and Quarrying                                      22.142373
Other service activities                                  12.218807
Professional, scientific and technical activities         18.964706
Public administration and defence; compulsory social      7.799366
Real estate activities                                    16.812121
Transportation and storage                                10.783960
Water supply, sewerage, waste management and              6.095714
Wholesale and retail trade; repair of motor vehicles and  14.942560

In [7]:
type(SectionHourly)

pandas.core.frame.DataFrame

In [8]:
SectionHourly.loc['Real estate activities']['DiffMeanHourlyPercent']

16.812121212121212

In [9]:
borig[borig['MainSection'] == 'Professional, scientific and technical activities']

,EmployerName,Address,CompanyNumber,SicCodes,DiffMeanHourlyPercent,DiffMedianHourlyPercent,DiffMeanBonusPercent,DiffMedianBonusPercent,MaleBonusPercent,FemaleBonusPercent,...,ResponsiblePerson,EmployerSize,CurrentName,SubmittedAfterTheDeadline,DueDate,DateSubmitted,Post,Val,MainSic,MainSection
24,6CATS UK LTD.,"1st Floor 1-3 Sun Street,\r\r\r\r\nLondon,\r\r\r\r\nEngland,\r\r\r\r\nEC2A 2EP",07284675,70229,15.0,6.0,NaN,NaN,0.0,0.0,...,Kirsty Henning (Finance Director),250 to 499,6Cats UK Ltd.,False,05/04/2019 00:00:00,02/04/2019 11:06:22,EC2A 2EP,True,70229,"Professional, scientific and technical activities"
27,A PEARSON HOLDINGS LIMITED,"Enterprise House,\r\r\r\r\n97 Alderley Road,\r\r\r\r\nWilmslow,\r\r\r\r\nCheshire,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nSK9 1PT",06532691,70100,14.9,9.2,NaN,NaN,0.0,0.0,...,Nikki Anderson (HR Director),500 to 999,A PEARSON HOLDINGS LIMITED,False,05/04/2019 00:00:00,04/04/2019 15:31:10,SK9 1PT,True,70100,"Professional, scientific and technical activities"
42,A.C. NIELSEN COMPANY LIMITED,"Nielsen House,\r\r\r\r\nJohn Smith Drive,\r\r\r\r\nOxford,\r\r\r\r\nOxfordshire,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nOX4 2WB",03263498,73200,9.5,2.9,26.5,26.4,57.0,54.0,...,Cathy Earle (HR Director UK & Ireland),500 to 999,A.C. NIELSEN COMPANY LIMITED,False,05/04/2019 00:00:00,04/04/2019 10:28:50,OX4 2WB,True,73200,"Professional, scientific and technical activities"
43,A.C.S. & T. GRIMSBY LTD.,"Linton Park, Linton,\r\r\r\r\nMaidstone,\r\r\r\r\nKent,\r\r\r\r\nME17 4AB",00515144,74990,-3.7,9.9,-39.1,22.2,83.0,89.0,...,Malcolm Johnstone (Managing Director),250 to 499,A.C.S. & T. GRIMSBY LTD.,False,05/04/2019 00:00:00,02/04/2019 09:47:03,ME17 4AB,True,74990,"Professional, scientific and technical activities"
65,ABARIS HOLDINGS LIMITED,"Chalfont House,\r\r\r\r\nOxford Road,\r\r\r\r\nDenham,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nUB9 4DX",01167325,70100,-3.8,5.0,NaN,12.7,44.5,26.0,...,Rachel Allen (Group HR Advisor),250 to 499,ABARIS HOLDINGS LIMITED,False,05/04/2019 00:00:00,04/04/2019 16:16:56,UB9 4DX,True,70100,"Professional, scientific and technical activities"
75,ABBOTT MEAD VICKERS.BBDO LIMITED,"Bankside 3 90-100 Southwark Street,\r\r\r\r\nLondon,\r\r\r\r\nEngland,\r\r\r\r\nSE1 0SW",01935786,73110,29.2,31.8,NaN,NaN,13.5,18.5,...,Kelly Knight (HR Director),250 to 499,ABBOTT MEAD VICKERS.BBDO LIMITED,False,05/04/2019 00:00:00,03/04/2019 08:50:58,SE1 0SW,True,73110,"Professional, scientific and technical activities"
90,ABERDEIN CONSIDINE,"5-9 Bon Accord Crescent,\r\r\r\r\nAberdeen,\r\r\r\r\nAB11 6DN",NaN,"68310,\r\r\r\r\n69102,\r\r\r\r\n70221",40.0,28.0,65.0,28.0,73.0,66.0,...,Jacqueline Law (Managing Partner),250 to 499,Aberdein Considine,False,05/04/2019 00:00:00,04/04/2019 16:59:56,AB11 6DN,True,68310,"Professional, scientific and technical activities"
111,ACCENTURE (UK) LIMITED,"30 Fenchurch Street,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nEC3M 3BD",04757301,70229,16.7,10.6,57.9,20.1,61.0,61.7,...,Olly Benzecry (Country Managing Director),"5000 to 19,999",ACCENTURE (UK) LIMITED,False,05/04/2019 00:00:00,18/01/2019 10:16:38,EC3M 3BD,True,70229,"Professional, scientific and technical activities"
171,ADAPTIMMUNE LIMITED,"60, Jubilee Avenue,\r\r\r\r\nMilton Park,\r\r\r\r\nAbingdon,\r\r\r\r\nOxfordshire,\r\r\r\r\nEngland,\r\r\r\r\nOX14 4RX",06456741,72190,9.5,18.2,-11.0,14.0,97.0,89.0,...,Nicky Smith (VP HR),250 to 499,ADAPTIMMUNE LIMITED,False,05/04/2019 00:00:00,03/04/2019 14:48:11,OX14 4RX,True,72190,"Professional, scientific and technical activities"
190,ADMIRAL LAW LIMITED,"9th Floor Brunel House, Fitzalan Road,\r\r\r\r\nCardiff,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nCF24 0EB",08023665,69102,7.7,0.0,40.5,34.5,61.3,56.7,...,Ceri Assiratti (Head of People Services /HR),250 to 499,ADMIRAL LAW LIMITED,False,05/04/2019 00:00:00,25/03/2019 08:39:12,CF24 0EB,True,69102,"Professional, scientific and technical activities"
205,ADVANCED MEDICAL SOLUTIONS GROUP PLC,"Premier Park, 33 Road One,\r\r\r\r\nWinsford Industrial Estate,\r\r\r\r\nWinsford,\r\r\r\r\nCheshire,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nCW7 3RT",02867684,70100,11.6,0.4,59.0,0.0,81.0,80.0,...,Catherine Tomlinson (Group HR Director),500 to 999,Advanced Medical Solutions Group PLC,False,05/04/2019 00:00:00,01/04/2019 12:23:49,CW7 3RT,True,70100,"Professional, scientific and technical activities"
206,ADVANCED PERSONNEL MANAGEMENT GROUP (UK) LIMITED,"Apm Unit 40, Newtown Shopping Centre,\r\r\r\r\nNewtown,\r\r\r\r\nBirmingham,\r\r\r\r\nEngland,\r\r\r\r\nB19 2SS",04881405,70100,13.3,2.9,-3.0,29.2,33.9,37.9,...,Juliet Mortiss (HR Director),250 to 499,ADVANCED PERSONNEL MANAGEMENT GROUP (UK) LIMITED,False,05/04/2019 00:00:00,24/03/2019 16:13:37,B19 2SS,True,70100,"Professional, scientific and technical activities"
215,AECOM INFRASTRUCTURE & ENVIRONMENT UK LIMITED,"Midpoint,\r\r\r\r\nAlencon Link,\r\r\r\r\nBasingstoke,\r\r\r\r\nHampshire,\r\r\r\r\nEngland,\r\r\r\r\nRG21 7PP",00880328,74901,21.4,22.1,40.0,21.0,14.0,14.0,...,"David Barwell (Chief Executive, UK & Ireland)",1000 to 4999,AECOM INFRASTRUCTURE & ENVIRONMENT UK LIMITED,False,05/04/2019 00:00:00,04/04/2019 08:56:11,RG21 7PP,True,74901,"Professional, scientific and technical activities"
216,AECOM LIMITED,"St George's House,\r\r\r\r\n5 St. George's Road,\r\r\r\r\nWimbledon,\r\r\r\r\nLondon,\r\r\r\r\nEngland,\r\r\r\r\nSW19 4DR",01846493,71122,20.6,20.6,27.0,56.0,18.0,18.0,...,"David Barwell (Chief Executive, UK & Ireland)",1000 to 4999,AECOM LIMITED,False,05/04/2019 00:00:00,04/04/2019 08:56:32,SW19 4DR,True,71122,"Professional, scientific and technical activities"
254,AGILENT TECHNOLOGIES LDA UK LIMITED,"5500 Lakeside Cheadle Royal Business Park,\r\r\r\r\nCheadle,\r\r\r\r\nCheshire,\r\r\r\r\nSK8 3GR",08815891,74909,24.4,27.0,33.7,35.8,85.6,88.7,...,Elaine Sutherland (UK & Ireland HR Mgr),250 to 499,AGILENT TECHNOLOGIES LDA UK LIMITED,False,05/04/2019 00:00:00,18/03/2019 16:02:17,SK8 3GR,True,74909,"Professional, scientific and technical activities"
292,AJ BELL PLC,"4 Exchange Quay,\r\r\r\r\nSalford Quays,\r\r\r\r\nManchester,\r\r\r\r\nEngland,\r\r\r\r\nM5 3EE",04503206,"70100,\r\r\r\r\n82990",29.2,8.3,70.3,19.9,74.5,73.2,...,Elizabeth Carrington (HR Director),500 to 999,AJ BELL PLC,False,05/04/2019 00:00:00,28/03/2019 17:16:22,M5 3EE,True,70100,"Professional, scientific and technical activities"
298,AKQA LIMITED,"1 St John's Lane,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nEC1M 4BL",02964394,73110,24.7,21.6,0.0,0.0,0.0,0.0,...,Ron Peterson (Managing Director),Less than 250,AKQA LIMITED,False,05/04/2019 00:00:00,01/03/2019 09:02:58,EC1M 4BL,True,73110,"Professional, scientific and technical activities"
299,AKT II LIMITED,"White Collar Factory, 1 Old Street Yard,\r\r\r\r\nLondon,\r\r\r\r\nEngland,\r\r\r\r\nEC1Y 8AF",07500271,71122,22.4,19.0,39.4,34.8,96.3,96.0,...,Gary Davison (Legal Director & Company Secretary),250 to 499,AKT II LIMITED,False,05/04/2019 00:00:00,04/04/2019 10:55:53,EC1Y 8AF,True,71122,"Professional, scientific and technical activities"
300,AKTRION MANUFACTURING SUPPORT SERVICES LIMITED,"Pemberton House,\r\r\r\r\nStafford Court Stafford Park 1,\r\r\r\r\nTelford,\r\r\r\r\nShropshire,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nTF3 3BD",03458202,"71122,\r\r\r\r\n71200,\r\r\r\r\n82990",-13.6,-17.9,-5.3,NaN,4.7,8.6,...,Kelly Howell (HR Director),250 to 499,AKTRION MANUFACTURING SUPPORT SERVICES LIMITED,False,05/04/2019 00:00:00,04/04/2019 15:14:59,TF3 3BD,True,71122,"Professional, scientific and technical activities"
312,ALCUMUS HOLDINGS LIMITED,"Axys House Heol Crochendy,\r\r\r\r\nParc Nantgarw,\r\r\r\r\nCardiff,\r\r\r\r\nWales,\r\r\r\r\nCF15 7TW",06955372,70100,22.0,37.0,32.0,40.0,44.0,40.0,...,Valerie Rees (Chief People Officer),500 to 999,ALCUMUS HOLDINGS LIMITED,False,05/04/2019 00:00:00,03/04/2019 14:11:45,CF15 7TW,True,70100,"Professional, scientific and technical activities"
324,ALERE TOXICOLOGY PLC,"21 Blacklands Way,\r\r\r\r\nAbingdon,\r\r\r\r\nOxfordshire,\r\r\r\r\nEngland,\r\r\r\r\nOX14 1DY",05396234,74909,8.0,-15.0,50.8,59.7,16.0,13.6,...,Nick Breare (General Manager),250 to 499,Alere Toxicology PLC,False,05/04/2019 00:00:00,04/04/2019 12:58:51,OX14 1DY,True,74909,"Professional, scientific and technical activities"
330,ALFRED H. KNIGHT INTERNATIONAL LIMITED,"Alfred H Knight Group Headquarters (Uk), Kings Business Park,\r\r\r\r\nKings Drive,\r\r\r\r\nPrescot,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nL34 1PJ",00900322,74909,17.4,10.3,43.3,16.2,91.6,90.2,...,Ian Baxter (Group CFO),250 to 499,ALFRED H. KNIGHT INTERNATIONAL LIMITED,False,05/04/2019 00:00:00,21/03/2019 07:26:50,L34 1PJ,True,74909,"Professional, scientific and technical activities"
346,ALLEN & OVERY SERVICE COMPANY LIMITED,"One,\r\r\r\r\nBishops Square,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nE1 6AD",02158783,74990,20.0,32.8,45.3,28.0,74.8,79.6,...,Sasha Hardman (Global HR Director),1000 to 4999,ALLEN & OVERY SERVICE COMPANY LIMITED,False,05/04/2019 00:00:00,02/10/2018 02:28:42,E1 6AD,True,74990,"Professional, scientific and technical activities"
352,ALLFORD HALL MONAGHAN MORRIS LIMITED,"Morelands,\r\r\r\r\n5 - 23 Old Street,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nEC1V 9HL",07155322,71111,24.9,16.7,35.2,22.5,79.4,72.4,...,Peter Morris (Managing Director),250 to 499,ALLFORD HALL MONAGHAN MORRIS LIMITED,False,05/04/2019 00:00:00,25/03/2019 09:47:50,EC1V 9HL,True,71111,"Professional, scientific and technical activities"
386,ALS ENVIRONMENTAL LIMITED,"Als Environmental Limited,\r\r\r\r\nTorrington Avenue,\r\r\r\r\nCoventry,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nCV4 9GU",02148934,71200,6.4,-4.1,52.0,96.7,3.9,2.1,...,Paul Holland (HR Manager),500 to 999,ALS ENVIRONMENTAL LIMITED,False,05/04/2019 00:00:00,25/03/2019 11:09:12,CV4 9GU,True,71200,"Professional, scientific and technical activities"
387,ALS LABORATORIES (UK) LIMITED,"Sands Mill,\r\r\r\r\nHuddersfield Road,\r\r\r\r\nMirfield,\r\r\r\r\nWest Yorkshire,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nWF14 9DQ",02391955,71200,-0.6,-5.9,53.4,86.7,10.9,11.2,...,Christine Davis (HR Manager),500 to 999,ALS LABORATORIES (UK) LIMITED,False,05/04/2019 00:00:00,29/03/2019 13:20:54,WF14 9DQ,True,71200,"Professional, scientific and technical activities"
389,ALTEN LTD,"1st, Floor 41 Moorgate,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nEC2R 6PP",08452862,74909,8.1,5.7,57.4,-73.0,26.6,23.5,...,Olivier Parsat (Chief Financial Officer),250 to 499,ALTEN LTD,False,05/04/2019 00:00:00,03/04/2019 17:05:29,EC2R 6PP,True,74909,"Professional, scientific and technical activities"
392,ALTODIGITAL MANAGED SERVICES LTD,"93 Vantage Point,\r\r\r\r\nKingswinford,\r\r\r\r\nWest Midlands,\r\r\r\r\nEngland,\r\r\r\r\nDY6 7FR",06380200,74909,23.6,19.2,39.6,27.8,56.2,46.2,...,Darrell Polden (Group Service and Operations Director),250 to 499,ALTODIGITAL MANAGED SERVICES LTD,False,05/04/2019 00:00:00,02/04/2019 17:09:15,DY6 7FR,True,74909,"Professional, scientific and technical activities"
396,ALTRAN UK LIMITED,"22 St Lawrence Street,\r\r\r\r\nBath,\r\r\r\r\nSomerset,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nBA1 1AN",03302507,71122,16.1,19.8,54.1,28.1,90.8,83.0,...,Michael Simms (Chief Executive Officer),250 to 499,ALTRAN UK LIMITED,False,05/04/2019 00:00:00,02/04/2019 12:21:14,BA1 1AN,True,71122,"Professional, scientific and technical activities"
409,AMARI METALS LIMITED,"Parkway House Unit 6, Parkway Industrial Estate,\r\r\r\r\nPacific Avenue,\r\r\r\r\nWednesbury,\r\r\r\r\nWest Midlands,\r\r\r\r\nEngland,\r\r\r\r\nWS10 7WP",02023155,70100,3.9,-4.3,32.9,-15.9,58.3,63.2,...,Morag Hale (Company Secretary),1000 to 4999,AMARI METALS LIMITED,False,05/04/2019 00:00:00,04/04/2019 16:59:47,WS10 7WP,True,70100,"Professional, scientific and technical activities"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10342,WAVEMAKER LIMITED,"Sea Containers,\r\r\r\r\n18 Upper Ground,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nSE1 9ET",04078547,73110,19.3,12.4,65.3,39.5,8.7,7.9,...,Paul Hutchison (CEO),500 to 999,WAVEMAKER LIMITED,False,05/04/2019 00:00:00,01/03/2019 10:23:21,SE1 9ET,True,73110,"Professional, scientific and technical activities"
10364,WEBB YATES ENGINEERS LIMITED,"48-50 Scrutton Street,\r\r\r\r\nLondon,\r\r\r\r\nEngland,\r\r\r\r\nEC2A 4HH",05393930,"71111,\r\r\r\r\n71122",9.5,7.5,8.2,0.0,62.5,61.5,...,Andy Yates (Director),Less than 250,WEBB YATES ENGINEERS LIMITED,False,05/04/2019 00:00:00,04/04/2019 09:01:02,EC2A 4HH,True,71111,"Professional, scientific and technical activities"
10405,WESSEX ARCHAEOLOGY LIMITED,"Portway House, Old Sarum Park,\r\r\r\r\nSalisbury,\r\r\r\r\nWiltshire,\r\r\r\r\nSP4 6EB",01712772,74909,7.6,2.2,NaN,NaN,0.0,0.0,...,Chris Brayne (CEO),250 to 499,WESSEX ARCHAEOLOGY LIMITED,False,05/04/2019 00:00:00,04/04/2019 12:09:08,SP4 6EB,True,74909,"Professional, scientific and technical activities"
10462,WESTGATE HEALTHCARE GROUP LIMITED,"Devonshire House 1,\r\r\r\r\nDevonshire Street,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nW1W 5DR",05969702,70100,-0.5,0.0,NaN,NaN,0.0,0.1,...,Ganesh Shetty (Head of Finance),250 to 499,WESTGATE HEALTHCARE GROUP LIMITED,False,05/04/2019 00:00:00,04/04/2019 17:04:44,W1W 5DR,True,70100,"Professional, scientific and technical activities"
10464,WESTGROVE GROUP (HOLDINGS) LIMITED,"940 Lakeside Drive,\r\r\r\r\nCentre Park,\r\r\r\r\nWarrington,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nWA1 1QY",09214794,74990,3.4,-0.1,100.0,-57.3,22.4,25.9,...,Helen Jones (HR Manager),500 to 999,WESTGROVE GROUP (HOLDINGS) LIMITED,False,05/04/2019 00:00:00,04/04/2019 12:23:09,WA1 1QY,True,74990,"Professional, scientific and technical activities"
10488,WH SMITH RETAIL HOLDINGS LIMITED,"Greenbridge Road,\r\r\r\r\nSwindon,\r\r\r\r\nWiltshire,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nSN3 3RX",00471941,70100,20.2,0.0,88.5,0.0,35.0,30.0,...,Anthony Lawrence (Group HR Director),"5000 to 19,999",WH SMITH RETAIL HOLDINGS LIMITED,False,05/04/2019 00:00:00,08/02/2019 13:54:46,SN3 3RX,True,70100,"Professional, scientific and technical activities"
10532,WILKIN CHAPMAN GROUP LTD,"Cartergate House,\r\r\r\r\n26 Chantry Lane,\r\r\r\r\nGrimsby,\r\r\r\r\nEngland,\r\r\r\r\nDN31 2LJ",05620938,69102,37.9,41.1,80.7,50.0,48.5,32.6,...,Des Mannion (Chief Executive Officer),250 to 499,Wilkin Chapman Group Ltd,False,05/04/2019 00:00:00,03/04/2019 16:39:49,DN31 2LJ,True,69102,"Professional, scientific and technical activities"
10555,WILLOWS VETERINARY GROUP,"Langdale House,\r\r\r\r\nGadbrook Business Park,\r\r\r\r\nRudheath,\r\r\r\r\nCW9 7TN",NaN,"1,\r\r\r\r\n75000",32.9,43.9,60.1,55.6,79.5,88.9,...,NaN,250 to 499,Willows Veterinary Group,False,31/03/2019 00:00:00,05/10/2018 12:28:11,CW9 7TN,True,75000,"Professional, scientific and technical activities"
10556,WILMINGTON PLC,"5th Floor 10 Whitechapel High Street,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nE1 8QS",03015847,70100,49.6,34.8,72.4,61.6,81.1,80.6,...,Tony Bainbridge (Group HR Director),Less than 250,Wilmington PLC,False,05/04/2019 00:00:00,02/04/2019 10:48:29,E1 8QS,True,70100,"Professional, scientific and technical activities"
10574,WINN SOLICITORS LIMITED,"Winn Solicitors, Brinkburn,\r\r\r\r\nStreet, Byker,\r\r\r\r\nNewcastle Upon Tyne,\r\r\r\r\nTyne & Wear,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nNE6 1PL",05084463,69102,26.4,11.0,80.1,45.7,76.9,77.5,...,Michael Warmington (HR Director),250 to 499,WINN SOLICITORS LIMITED,False,05/04/2019 00:00:00,27/03/2019 08:52:53,NE6 1PL,True,69102,"Professional, scientific and technical activities"
10613,WOOD NUCLEAR LIMITED,"Booths Park, Chelford Road,\r\r\r\r\nKnutsford,\r\r\r\r\nCheshire,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nWA16 8QZ",01120437,"42220,\r\r\r\r\n71121,\r\r\r\r\n71122,\r\r\r\r\n71200",25.8,25.4,37.5,39.5,35.7,29.5,...,Sue MacDonald (Executive President - People & Organisation),500 to 999,WOOD NUCLEAR LIMITED,False,05/04/2019 00:00:00,25/02/2019 09:36:43,WA16 8QZ,True,42220,"Professional, scientific and technical activities"
10643,WORLEYPARSONS EUROPE LIMITED,"27 Great West Road,\r\r\r\r\nBrentford,\r\r\r\r\nEngland,\r\r\r\r\nTW8 9BW",04334425,"71111,\r\r\r\r\n71121,\r\r\r\r\n71122",34.5,42.0,21.2,-0.3,20.4,13.8,...,"Ron Jackson (Remuneration & Benefits Manager, Europe, Middle East and Africa)",500 to 999,WORLEYPARSONS EUROPE LIMITED,False,05/04/2019 00:00:00,26/03/2019 08:21:47,TW8 9BW,True,71111,"Professional, scientific and technical activities"
10647,WPP 2005 LIMITED,"Sea Containers House,\r\r\r\r\n18 Upper Ground,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nSE1 9GL",01003653,70100,45.0,34.0,98.0,66.0,63.0,53.0,...,Karen Blackett (UK Country Manager),"5000 to 19,999",WPP 2005 LIMITED,False,05/04/2019 00:00:00,01/03/2019 09:18:07,SE1 9GL,True,70100,"Professional, scientific and technical activities"
10648,WPP BRANDS (UK) LIMITED,"Greater London House,\r\r\r\r\nHampstead Road,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nNW1 7QP",00390845,73110,24.8,16.3,57.8,26.7,19.6,15.7,...,Ian Gary Paul (Director),1000 to 4999,WPP BRANDS (UK) LIMITED,False,05/04/2019 00:00:00,01/03/2019 10:02:37,NW1 7QP,True,73110,"Professional, scientific and technical activities"
10652,WRIGHT HASSALL LEAMINGTON LIMITED,"Olympus Avenue,\r\r\r\r\nLeamington Spa,\r\r\r\r\nWarwickshire,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nCV34 6BF",02853717,69102,33.4,36.7,18.1,58.1,8.0,9.0,...,Paul Gregson (HR Director),250 to 499,WRIGHT HASSALL LEAMINGTON LIMITED,False,05/04/2019 00:00:00,28/03/2019 16:56:08,CV34 6BF,True,69102,"Professional, scientific and technical activities"
10653,WRIGHT LEISURE LIMITED,"Unit 1 Kirkstall Industrial Estate,\r\r\r\r\nKirkstall Road, Burley,\r\r\r\r\nLeeds,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nLS4 2AZ",07572128,"70100,\r\r\r\r\n93130",22.0,16.4,26.1,39.2,70.7,67.3,...,Helen Gauden (Chief Financial Officer),500 to 999,WRIGHT LEISURE LIMITED,False,05/04/2019 00:00:00,04/04/2019 08:13:38,LS4 2AZ,True,70100,"Professional, scientific and technical activities"
10657,WSP MANAGEMENT SERVICES LIMITED,"Wsp House,\r\r\r\r\n70 Chancery Lane,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nWC2A 1AF",02454665,74909,37.5,34.2,87.9,41.7,29.4,22.4,...,Paul Newing (UK Human Resources Director),500 to 999,WSP MANAGEMENT SERVICES LIMITED,False,05/04/2019 00:00:00,25/03/2019 16:21:47,WC2A 1AF,True,74909,"Professional, scientific and technical activities"
10658,WSP UK LIMITED,"Wsp House,\r\r\r\r\n70 Chancery Lane,\r\r\r\r\nLondon,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nWC2A 1AF",01383511,71122,21.6,22.8,39.7,20.0,23.0,19.6,...,Paul Newing (UK Human Resources Director),"5000 to 19,999",WSP UK LIMITED,False,05/04/2019 00:00:00,25/03/2019 16:00:46,WC2A 1AF,True,71122,"Professional, scientific and technical activities"
10668,WYEVALE GARDEN CENTRES HOLDINGS LIMITED,"Wyevale Garden Centres Syon Park, London Road,\r\r\r\r\nBrentford,\r\r\r\r\nMiddlesex,\r\r\r\r\nEngland,\r\r\r\r\nTW8 8JF",01972554,70100,17.1,0.0,-0.9,NaN,1.2,0.2,...,Anthony Jones (Director),1000 to 4999,WYEVALE GARDEN CENTRES HOLDINGS LIMITED,False,05/04/2019 00:00:00,29/03/2019 11:55:21,TW8 8JF,True,70100,"Professional, scientific and technical activities"
10669,WYG ENGINEERING LIMITED,"Arndale Court Otley Road,\r\r\r\r\nHeadingley,\r\r\r\r\nLeeds,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nLS6 2UJ",01959704,71129,42.3,42.6,NaN,NaN,0.0,0.0,...,Rich Roberts (Group HR Director),250 to 499,WYG ENGINEERING LIMITED,False,05/04/2019 00:00:00,04/04/2019 09:16:54,LS6 2UJ,True,71129,"Professional, scientific and technical activities"
10670,WYG ENVIRONMENT PLANNING TRANSPORT LIMITED,"Arndale Court Otley Road,\r\r\r\r\nHeadingley,\r\r\r\r\nLeeds,\r\r\r\r\nUnited Kingdom,\r\r\r\r\nLS6 2UJ",03050297,"71112,\r\r\r\r\n71122,\r\r\r\r\n71129",22.4,18.2,NaN,NaN,0.0,0.0,...,Rich Roberts (Group HR Director),250 to 499,WYG ENVIRONMENT PLANNING TRANSPORT LIMITED,False,05/04/2019 00:00:00,04/04/2019 09:38:35,LS6 2UJ,True,71112,"Professional, scientific and technical activities"

In [10]:
sic_dict_1={'Manufacturing':'Manufacturing',
            'Administrative and Support Services':'Administrative and support service activities',
            'Education':'Education',
            'Retail Trade and Automobiles':'Wholesale and retail trade; repair of motor vehicles and',
            'Health and Social Work':'Human health and social work activities',
            'Professional and Scientific Services':'Professional, scientific and technical activities',
            'Accommodation and Food Services':'Accommodation and food service activities',
            'Public Administration and Defence':'Public administration and defence; compulsory social',
            'IT and Communications':'Information and communication',
            'Financial and Insurance Services':'Financial and insurance activities',
            'Transportation and Storage':'Transportation and storage',
            'Construction':'Construction',
            'Arts, Entertainment and Recreation':'Arts, entertainment and recreation',
            'Other Services':'Other service activities',
            'Real Estate':'Real estate activities'}

In [11]:
sic_dict_2={'Manufacturing':'Manufacturing',
            'Administrative and support service activities':'Administrative and Support Services',
            'Education':'Education',
            'Wholesale and retail trade; repair of motor vehicles and':'Retail Trade and Automobiles',
            'Human health and social work activities':'Health and Social Work',
            'Professional, scientific and technical activities':'Professional, Scientific and Technical Services',
            'Accommodation and food service activities':'Accommodation and Food Services',
            'Public administration and defence; compulsory social':'Public Administration and Defence',
            'Information and communication':'IT and Communications',
            'Financial and insurance activities':'Financial and Insurance Services',
            'Transportation and storage':'Transportation and Storage',
            'Construction':'Construction',
            'Arts, entertainment and recreation':'Arts, Entertainment and Recreation',
            'Other service activities':'Other Services',
            'Real estate activities':'Real Estate'}

In [13]:
# test = [{'label':name, 'value':sic_dict.get(name)} for name in sic_dict],

# test

In [14]:
pal = sns.color_palette("Set2")
print(pal.as_hex())

['#66c2a5', '#fc8d62', '#8da0cb', '#e78ac3', '#a6d854', '#ffd92f']

In [15]:
import random

In [16]:
rand_list = list(sic_dict_2.keys())

In [17]:
rand_1 = random.choice(rand_list)
print(rand_1)

Administrative and support service activities

In [18]:
remain_list = rand_list
remain_list.remove(rand_1)

rand_2 = random.choice(remain_list)
print(rand_2)

Other service activities

In [26]:
borig['MainSection'].value_counts()

Manufacturing                                               1385
Administrative and support service activities               1264
Education                                                   1223
Wholesale and retail trade; repair of motor vehicles and    1008
Human health and social work activities                     988
Professional, scientific and technical activities           714
Accommodation and food service activities                   563
Public administration and defence; compulsory social        473
Information and communication                               452
Financial and insurance activities                          414
Transportation and storage                                  399
Construction                                                329
Arts, entertainment and recreation                          295
Other service activities                                    218
Real estate activities                                      132
Water supply, sewerage, waste management and                70
Mining and Quarrying                                        59
Electricity, gas, steam and air conditioning supply         59
Agriculture, Forestry and Fishing                           48
Activities of extraterritorial organisations and            9
Activities of households as employers; undifferentiated     4
Name: MainSection, dtype: int64

In [25]:
len(borig[borig['MainSection'] == 'Manufacturing'])

1385